spring:
  application:
    name: miro

  profiles:
    include: auth
    active: dev

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true