spring:
  application:
    name: miro

  profiles:
    active: test

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  config:
    import: "classpath:/application-secret.yml"

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
