spring:
  application:
    name: miro

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  config:
    import: "classpath:/application-secret.yml"

  mail:
    host: smtp.gmail.com
    port: 587
    username: hobby0519@gmail.com
    password: "asd"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000