spring:
  security:
    oauth2:
      client:
        registration:
          # 구글 로그인 추가
          google:
            client-id: 991882204649-m7pm4n974qb2ccro0m7ifh96mcnt3h13.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - email
              - profile
oauth2:
  login-url: https://accounts.google.com/o/oauth2/v2/auth
  client-id: 991882204649-m7pm4n974qb2ccro0m7ifh96mcnt3h13.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: http://localhost:8080/api/v1/user/login/oauth2/code/google
  token-uri: https://oauth2.googleapis.com/token
  user-info-uri: https://www.googleapis.com/userinfo/v2/me
jwt:
  secret: 4dovQZNFIk94YJfgIfD9ercBD_9DyGNAmQ4keHYImm8