spring:
  application:
    name: miro

  profiles:
    include: auth
    active: ryul

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  config:
    import: "classpath:/application-secret.yml"

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
